name: Multi-OS Package Builder

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted, temp]
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: alma9
            image: almalinux:9
            code: el9
            repo: alma
            folder: packages
            script: .github/scripts/rpm/alma/9.sh

          - name: debian12
            image: debian:12
            code: bookworm
            repo: debian
            folder: packages
            script: .github/scripts/deb/debian/12.sh

          - name: ubuntu2404
            image: ubuntu:24.04
            code: noble
            repo: ubuntu
            folder: packages
            script: .github/scripts/deb/ubuntu/24.04.sh

    container:
      image: ${{ matrix.image }}
      options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read version from VERSION file
        id: version
        run: echo "PHP_PACK_VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Run Build Script
        run: |
          chmod +x ${{ matrix.script }}
          ${{ matrix.script }}
        env:
          BUILD_NAME: ${{ matrix.name }}
          BUILD_IMAGE: ${{ matrix.image }}
          BUILD_CODE: ${{ matrix.code }}
          BUILD_REPO: ${{ matrix.repo }}
          BUILD_FOLDER: ${{ matrix.folder }}
          UPLOAD_USER: ${{ secrets.UPLOAD_USER }}
          UPLOAD_PASS: ${{ secrets.UPLOAD_PASS }}
          BUILD_CORES: '70'
          DOMAIN: 'de.repo.raweb.al'
          PHP_VERSION_MAJOR: '8.4'
          PHP_PACK_VERSION: ${{ env.PHP_PACK_VERSION }}
