name: Multi-OS Package Builder

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: [self-hosted, temp]
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: alma8
            image: almalinux:8
            code: el8
            repo: alma
            folder: packages
            script: ./scripts/rpm/alma/8.sh

          - name: alma9
            image: almalinux:9
            code: el9
            repo: alma
            folder: packages
            script: ./scripts/rpm/alma/9.sh

          - name: debian11
            image: debian:11
            code: bullseye
            repo: debian
            folder: packages
            script: ./scripts/deb/debian/11.sh

          - name: debian12
            image: debian:12
            code: bookworm
            repo: debian
            folder: packages
            script: ./scripts/deb/debian/12.sh

          - name: ubuntu2204
            image: ubuntu:22.04
            code: jammy
            repo: ubuntu
            folder: packages
            script: ./scripts/deb/ubuntu/22.04.sh

          - name: ubuntu2404
            image: ubuntu:24.04
            code: noble
            repo: ubuntu
            folder: packages
            script: ./scripts/deb/ubuntu/24.04.sh

    container:
      image: ${{ matrix.image }}
      options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Build Script
        run: |
          chmod +x ${{ matrix.script }}
          ${{ matrix.script }}
        env:
          BUILD_NAME: ${{ matrix.name }}
          BUILD_IMAGE: ${{ matrix.image }}
          BUILD_CODE: ${{ matrix.code }}
          BUILD_REPO: ${{ matrix.repo }}
          BUILD_FOLDER: ${{ matrix.folder }}
          UPLOAD_USER: ${{ secrets.UPLOAD_USER }}
          UPLOAD_PASS: ${{ secrets.UPLOAD_PASS }}
          PHP_VERSION_MAJOR: '8.4'
          BUILD_CORES: '70'
          DOMAIN: 'repo.julio.al'
